version: 2
jobs:
  test:
    docker:
      - image: danielflook/python-minifier-build
    steps:
      - checkout

      - run:
          name: Set version statically
          command: |
            VERSION=$(python setup.py --version)
            sed -i "s/setup_requires=.*/version='$VERSION',/; s/use_scm_version=.*//" setup.py

      - run:
          name: tox
          command: |
            pip install -r requirements-dev.txt
            tox -r

  publish:
    docker:
      - image: danielflook/python-minifier-build
    steps:
      - checkout

      - run:
          name: Set version statically
          command: |
            VERSION=$(python setup.py --version)
            sed -i "s/setup_requires=.*/version='$VERSION',/; s/use_scm_version=.*//" setup.py

      - run:
          name: Add signing key
          command: |
            echo $SIGNING_KEY | base64 -d > private.key
            gpg --import private.key

      - run:
          name: sdist
          command: |
            pip3 install --upgrade setuptools wheel twine
            python3 setup.py sdist bdist_wheel

            if [[ "$(python setup.py --version)" != *"+"* ]]; then
              twine upload --sign dist/*
            fi

      - store_artifacts:
          path: dist/

  publish_docs:
    docker:
      - image: danielflook/python-minifier-build
    steps:
      - checkout

      - run:
          name: sphinx build
          command: |
            pip3 install --upgrade setuptools wheel twine
            pip3 install -r requirements-dev.txt
            python3 setup.py install
            sphinx-build docs/source /tmp/build

      - run:
          name: git push
          command: |
            git config user.email "daniel@flook.org"
            git config user.name "Daniel Flook"

            git checkout gh-pages
            rm -rf * .circleci
            cp -R /tmp/build/. .
            git add --all
            git commit -m "Update docs" || true
            git push

workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish_docs:
          requires:
            - publish
